default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  <<: *local
  database: <%= ENV['DEVELOPMENT_DATABASE'] %>

test:
  <<: *default
  <<: *local
  database: <%= ENV['TEST_DATABASE'] %>

production:
  <<: *default
  url: 