default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: <%= ENV['DEVELOPMENT_DATABASE'] || "todo_development" %>

test:
  <<: *default
  database: <%= ENV['TEST_DATABASE'] || "todo_test" %>

production:
  <<: *default
  database: <%= ENV['PRODUCTION_DATABASE'] %>
